services:
  brokage-firm:
    container_name: brokage-firm
    build:
      context: .
      dockerfile: Dockerfile
    image: brokage-firm
    ports:
      - "8081:8081"
    networks:
      - brokage
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/brokage_firm
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brokage_firm
    ports:
      - "5432:5432"
    networks:
      - brokage

networks:
  brokage:
